/** Mock pricing content for the Pricing page. Illustrative figures only. */

export interface PricingTier {
  name: string;
  fee: string;
  feeNote: string;
  tagline: string;
  cta: string;
  featured: boolean;
  features: string[];
}

export const PRICING_TIERS: PricingTier[] = [
  {
    name: "Starter",
    fee: "5%",
    feeNote: "of yield",
    tagline: "Self-serve. Get a test key and ship.",
    cta: "Start free",
    featured: false,
    features: [
      "Embeddable yield widget",
      "USDC vault on Arc testnet",
      "SDK + REST API",
      "Webhooks",
      "Community support",
    ],
  },
  {
    name: "Growth",
    fee: "5%",
    feeNote: "of yield",
    tagline: "For teams going live with real volume.",
    cta: "Get API key",
    featured: true,
    features: [
      "Everything in Starter",
      "Live vaults + all assets",
      "Configurable fee share",
      "cNGN ⇄ USDC FX swap",
      "Priority support + SLA",
    ],
  },
  {
    name: "Enterprise",
    fee: "Custom",
    feeNote: "",
    tagline: "Custom economics and dedicated infra.",
    cta: "Talk to us",
    featured: false,
    features: [
      "Everything in Growth",
      "Custom fee-share terms",
      "Dedicated vaults",
      "White-glove onboarding",
      "Custom compliance review",
    ],
  },
];

export interface PricingFaq {
  q: string;
  a: string;
}

export const PRICING_FAQS: PricingFaq[] = [
  {
    q: "How does the fee share actually work?",
    a: "EarnIT takes a flat 5% performance fee on gross yield. The remaining 95% is split between your users and you, based on the share you configure. You set how much value flows to your users versus your own revenue line.",
  },
  {
    q: "Are there any platform or seat fees?",
    a: "No. There are no monthly minimums, seat fees, or setup costs. You only pay the 5% performance fee, and only on yield that is actually generated.",
  },
  {
    q: "When and how do payouts happen?",
    a: "Fee-share earnings accrue continuously and are paid out on a configurable schedule to your designated payout address. You can track accruals in real time from the dashboard.",
  },
  {
    q: "What assets and currencies are supported?",
    a: "USDC, EURC, and cNGN today, with USD and NGN display currencies. Local-currency deposits are routed into dollar yield via an FX swap and returned in the display currency.",
  },
  {
    q: "Is the yield regulated?",
    a: "Yield is generated by Circle USYC, a tokenized US-treasury fund. Vaults are non-custodial ERC-4626 contracts settling on Arc.",
  },
];

/** Compact money formatter shared by the calculator: $1.2M / $340K / $920. */
export function formatMoney(n: number): string {
  const a = Math.abs(n);
  if (a >= 1e6) return "$" + (n / 1e6).toFixed(2).replace(/\.00$/, "") + "M";
  if (a >= 1e3) return "$" + (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return "$" + Math.round(n).toLocaleString("en-US");
}
